### ISSUE TITLE
Robot Controller Fails to start InflateException org.opencv.android.JavaCameraView

### ISSUE THREAD

**Issue by jgroppe10836** [trc492/FtcSamples#2]
Our team is unable to try the trc4943 lib. After building the FTC Robot Controller app fails to start. 

Is this a build issue? I'd be happy to supply you with any information you may need about our dev environment.

Motorola E4
Android: 7.1.1

> 

02/08 22:17:53: Launching TeamCode
No apk changes detected since last installation, skipping installation of C:\dev\FtcSamples\TeamCode\build\outputs\apk\debug\TeamCode-debug.apk
$ adb shell am force-stop com.qualcomm.ftcrobotcontroller
$ adb shell am start -n "com.qualcomm.ftcrobotcontroller/org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7153 on device motorola-moto_e__4_-ZY2252JJWF
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/art: Late-enabling -Xcheck:jni
V/AppUtil: initializing: getExternalStorageDirectory()=/storage/emulated/0
V/RobotCore: saving logcat to /storage/emulated/0/robotControllerLog.txt
    logging command line: exec logcat -f /storage/emulated/0/robotControllerLog.txt -r4096 -n4 -v threadtime UsbRequestJNI:S UsbRequest:S art:W ThreadPool:W System:W ExtendedExtractor:W OMXClient:W MediaPlayer:W dalvikvm:W  *:V
V/ServiceStarter: attempting to start service MediaTransferProtocolMonitorService
V/ServiceStarter: started service MediaTransferProtocolMonitorService
V/ServiceStarter: attempting to start service OnBotJavaService
V/ServiceStarter: started service OnBotJavaService
V/AppUtil: rootActivity=FtcRobotControllerActivity
V/RCActivity: onCreate()
V/RCActivity: rootActivity is of class FtcRobotControllerActivity
V/ThreadPool: container(0x0c3c546c: CallbackLooper) added id=612 TID=0 count=1
V/CallbackLooper: thread=612
V/NetDiscover_wifiDirectAgent: doStart()...
I/RobotCore: Done running ps
V/NetDiscover_wifiDirectAgent_bcast: wifiP2pEnabled=true
D/NetDiscover_wifiDirectAgent_bcast: connection changed: networkInfo.state=UNKNOWN
V/NetDiscover_wifiDirectAgent_bcast: NetworkInfo: [type: WIFI_P2P[], state: UNKNOWN/IDLE, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false, metered: false]
    WifiP2pInfo: groupFormed: false isGroupOwner: false groupOwnerAddress: null mccMode: false
    WifiP2pGroup: network: null, isGO: false, GO: null, interface: null, networkId: 0
V/NetDiscover_wifiDirectAgent: ...doStart()
V/NetDiscover_name: doStart()...
V/NetDiscover_name: ...doStart()
V/NetDiscover_wifiDirectAgent_bcast: this device changed: Device=10836-D-RC deviceAddress=0e:cb:85:e6:ab:e0 primary type=10-0050F204-5 secondary type=null wps=0 grpcapab=0 devcapab=0 status=3 wfdInfo=WFD enabled=falseWFD DeviceInfo=0 WFD CtrlPort=0 WFD MaxThroughput=0 level=0
V/NetDiscover_prefremrc: ----- all preferences -----
V/NetDiscover_name: remembering wifiDirectName: 10836-D-RC...
    wifiDirectName=10836-D-RC
V/NetDiscover_prefremrc: name='pref_app_theme' value=red
V/NetDiscover_name: ...remembering wifiDirectName
V/NetDiscover_prefremrc: doStart()...
V/NetDiscover_wifiDirectAgent_bcast: wifi direct remembered groups cleared
V/NetDiscover_prefremrc: ...doStart()
V/NetDiscover_wifiDirectAgent_bcast: wifiState=ENABLED
V/NetDiscover_wifiDirectAgent: found persistent group: DIRECT-2X-10836-D-RC
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qualcomm.ftcrobotcontroller, PID: 7153
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qualcomm.ftcrobotcontroller/org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity}: android.view.InflateException: Binary XML file line #89: Binary XML file line #46: Error inflating class org.opencv.android.JavaCameraView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2690)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6196)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
     Caused by: android.view.InflateException: Binary XML file line #89: Binary XML file line #46: Error inflating class org.opencv.android.JavaCameraView
     Caused by: android.view.InflateException: Binary XML file line #46: Error inflating class org.opencv.android.JavaCameraView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.opencv.android.JavaCameraView" on path: DexPathList[[zip file "/data/app/com.qualcomm.ftcrobotcontroller-1/base.apk"],nativeLibraryDirectories=[/data/app/com.qualcomm.ftcrobotcontroller-1/lib/arm, /system/fake-libs, /data/app/com.qualcomm.ftcrobotcontroller-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:609)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412)
        at android.app.Activity.setContentView(Activity.java:2429)
        at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:267)
        at android.app.Activity.performCreate(Activity.java:6698)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2643)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6196)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Application terminated.
>

**Comment by trc492** [comment]
Don't know what is trc4943 lib. I assume you are referring to our library. Are you building an exact clone of our FtcSamples project? If so, I don't have any build issue with it. If you have cloned our FtcSamples but made modifications to it, then I wouldn't know what caused the build issue. From the info above, it seems you have issues using OpenCV JavaCameraView class. The stack dump didn't even contain anything related to our library. It seems it is complaining that class is not found. Did you by chance not importing OpenCV correctly? Sorry I couldn't offer much help since I do not know what your project looks like.

**Comment by trc492** [comment]
Also, from the info above, your issue is not build but runtime. Build issue means the project failed to build. But it looks like your project built fine and deployed. It just hit an exception during runtime. Is that true?

**Comment by trc492** [comment]
Stale issue with no response from OP.
